### ISSUE TITLE
Pip2.7 installation fails out-of-the-box

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#161]
Using always Python3 with APKiD, but I needed it to run in an environment with only Python2. 

```sh
$  which apkid
apkid is /usr/local/bin/apkid

$ apkid
Traceback (most recent call last):
  File "/usr/local/bin/apkid", line 6, in <module>
    from apkid.main import main
  File "/usr/local/lib/python2.7/dist-packages/apkid/main.py", line 11
    description=f"APKiD - Android Application Identifier v{__version__}",
                                                                       ^
SyntaxError: invalid syntax
```

I'm assuming that there are so many py3-like print formatting around the code...
```sh
>  ipython 
Python 2.7.12 (default, Aug 22 2019, 16:36:40) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: __version__= 1

In [2]: description=f"APKiD - Android Application Identifier v{__version__}"
  File "<ipython-input-2-4293b553dfb2>", line 1
    description=f"APKiD - Android Application Identifier v{__version__}"
                                                                       ^
SyntaxError: invalid syntax


In [3]: description="APKiD - Android Application Identifier v{0}".format(__version__)

In [4]: 
```

**Comment by enovella** [comment]
Same behavior observed in Python3
```sh
 > apkid
Traceback (most recent call last):
  File "/usr/local/bin/apkid", line 7, in <module>
    from apkid.main import main
  File "/usr/local/lib/python3.5/dist-packages/apkid/main.py", line 11
    description=f"APKiD - Android Application Identifier v{__version__}",
                                                                       ^
SyntaxError: invalid syntax

```

**Comment by strazzere** [comment]
Are you sure something on that system isn't borked? Fresh install on my machine using Python 3.6.8;

```
$ pip3 uninstall apkid
Uninstalling apkid-2.1.0:
  Would remove:
    /home/diff/.local/lib/python3.6/site-packages/apkid.egg-link
Proceed (y/n)? Y
  Successfully uninstalled apkid-2.1.0
$ git pull
Already up to date.
$ ./prep-release.py 
[*] Compiling Yara files
[*] Saved 162 rules to /home/diff/repo/android/APKiD/apkid/rules/rules.yarc
[*] Rules hash: b195770153d7fa9b17a05be46163e77200e9fea04e52540bc2a8ff1896be34e0
[*] Rule tag counts:
 |-> abnormal: 2
 |-> anti_debug: 1
 |-> anti_disassembly: 3
 |-> anti_vm: 28
 |-> compiler: 10
 |-> dropper: 2
 |-> embedded: 1
 |-> file_type: 3
 |-> internal: 15
 |-> manipulator: 1
 |-> obfuscator: 28
 |-> packer: 69
 |-> protector: 1
[*] Finished preparing APKiD for release.
$ pip3 install -e . --user
Obtaining file:///home/diff/repo/android/APKiD
Requirement already satisfied: yara-python==3.10.0 in /usr/local/lib/python3.6/dist-packages/yara_python-3.10.0-py3.6-linux-x86_64.egg (from apkid==2.1.0) (3.10.0)
Requirement already satisfied: argparse in /home/diff/.local/lib/python3.6/site-packages (from apkid==2.1.0) (1.4.0)
Installing collected packages: apkid
  Running setup.py develop for apkid
Successfully installed apkid
$ apkid
[+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
```

**Comment by strazzere** [comment]
Are you building it from source? Or just trying to install via `pip`?

**Comment by enovella** [comment]
> Are you building it from source? Or just trying to install via `pip`?

pip only

**Comment by enovella** [comment]
> Are you sure something on that system isn't borked? Fresh install on my machine using Python 3.6.8;
> 
> ```
> $ pip3 uninstall apkid
> Uninstalling apkid-2.1.0:
>   Would remove:
>     /home/diff/.local/lib/python3.6/site-packages/apkid.egg-link
> Proceed (y/n)? Y
>   Successfully uninstalled apkid-2.1.0
> $ git pull
> Already up to date.
> $ ./prep-release.py 
> [*] Compiling Yara files
> [*] Saved 162 rules to /home/diff/repo/android/APKiD/apkid/rules/rules.yarc
> [*] Rules hash: b195770153d7fa9b17a05be46163e77200e9fea04e52540bc2a8ff1896be34e0
> [*] Rule tag counts:
>  |-> abnormal: 2
>  |-> anti_debug: 1
>  |-> anti_disassembly: 3
>  |-> anti_vm: 28
>  |-> compiler: 10
>  |-> dropper: 2
>  |-> embedded: 1
>  |-> file_type: 3
>  |-> internal: 15
>  |-> manipulator: 1
>  |-> obfuscator: 28
>  |-> packer: 69
>  |-> protector: 1
> [*] Finished preparing APKiD for release.
> $ pip3 install -e . --user
> Obtaining file:///home/diff/repo/android/APKiD
> Requirement already satisfied: yara-python==3.10.0 in /usr/local/lib/python3.6/dist-packages/yara_python-3.10.0-py3.6-linux-x86_64.egg (from apkid==2.1.0) (3.10.0)
> Requirement already satisfied: argparse in /home/diff/.local/lib/python3.6/site-packages (from apkid==2.1.0) (1.4.0)
> Installing collected packages: apkid
>   Running setup.py develop for apkid
> Successfully installed apkid
> $ apkid
> [+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
> ```

Didn't remember that Python2 support was deprecated. Using Ubuntu 16.04 LTS

**Comment by enovella** [comment]
APKiD from pip2 should be removed. OTOH, I just realized that my python3 is 3.5 and APKiD needs 3.6 onwards

**Comment by CalebFenton** [comment]
Apkid is python 3.6+ compatible. Even have a little badge for this at
https://pypi.org/project/apkid/.

Errors you're getting are from f-strings.

**Comment by enovella** [comment]
Fixed.

**Comment by dskvr** [comment]
This is still happening, on all `py2` compatible tags. 

```
python2.7/site-packages/nox/__main__.py", line 113
    print(dist.version, file=sys.stderr)
                            ^
SyntaxError: invalid syntax
```

Yes, `python2` is deprecated, tell that to **Unreal Engine**

**Comment by strazzere** [comment]
I would suggest using either the docker version or upgrading withing pyenv. We are not actively providing support for `python2`, I'm pretty sure the code base has already been tuned enough towards python3.6+. You're welcome to edit the files yourself to try and get some `python2` support out of it, though this doesn't feel like the correct solution, and we wouldn't be looking to merge that into any of these branches unless it maintains forward compatibility.

RE: Unreal Engine -- sorry brother, that dumpster fire is something else :D
